name: aplikasi_mobile_lanjut
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  cloud_firestore: ^6.4.1
  image_picker: ^1.2.2
  flutter_markdown_plus: ^1.0.7
  dynamic_color: ^1.7.0
  provider: ^6.1.5
  supabase_flutter: ^2.12.4
  firebase_messaging: ^16.2.2
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.5.5
  pdf: ^3.12.0
  printing: ^5.14.3
  intl: ^0.20.2
  flutter_gemma: ^0.16.1
  dio: ^5.7.0
  markdown: ^7.2.2
  restart_app: ^1.8.3
  permission_handler: ^12.0.1
  marquee: ^2.3.0
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

dependency_overrides:
  large_file_handler: ^0.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/materi/
    - assets/dokumentasi/
    - assets/background/
    - lib/task6/.env
