org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
kotlin.incremental=false

# Tetap matikan fitur AGP 9+ DSL agar kompatibel dengan Flutter 3.12
android.newDsl=false
# Enable Built-in Kotlin with specific version override from settings.gradle.kts
android.builtInKotlin=true
android.experimental.privacysandbox.sdk.enable=false
