// File generated by flutterfire_cli
// Replace dengan konfigurasi Firebase Anda sendiri

import 'dart:io';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (Platform.isAndroid) {
      return android;
    } else if (Platform.isIOS) {
      return ios;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions tidak tersedia untuk platform ini.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.aplikasiMobileLanjut',
  );
}

// ========== INSTRUKSI SETUP FIREBASE ==========

// OPSI 1: Menggunakan FlutterFire CLI (Disarankan)
// 1. Install FlutterFire CLI:
//    flutter pub global activate flutterfire_cli
// 
// 2. Jalankan command:
//    flutterfire configure
// 
// 3. Pilih Firebase project Anda dari daftar
// 4. CLI akan generate file firebase_options.dart dan setup otomatis
// 5. Replace file ini dengan hasil generate dari CLI

// OPSI 2: Setup Manual
// 1. Buat Firebase project di https://console.firebase.google.com
// 2. Tambahkan aplikasi:
//    a. Android: Download google-services.json
//    b. iOS: Download GoogleService-Info.plist
// 3. Place file di folder yang sesuai:
//    - Android: android/app/
//    - iOS: ios/Runner/
// 4. Update credentials di file ini
// 5. Built app dengan: flutter build

// ========== KONFIGURASI YANG DIPERLUKAN ==========

// Replace nilai berikut dengan konfigurasi Firebase Anda:
// - apiKey: API key untuk aplikasi
// - appId: ID aplikasi di Firebase
// - messagingSenderId: Sender ID untuk Firebase Cloud Messaging
// - projectId: Project ID dari Firebase Console
// - storageBucket: Storage bucket untuk Firebase Storage
// - iosBundleId: Bundle ID untuk iOS app

// ========== LANGKAH-LANGKAH SETELAH SETUP ==========

// 1. Enable Authentication:
//    - Buka Firebase Console
//    - Pilih Authentication
//    - Enable Email/Password Sign-in method

// 2. Setup Firestore Database:
//    - Buka Firestore Database
//    - Pilih mode: Start in test mode (untuk development)
//    - Create collections sesuai struktur di week5_data_format.dart

// 3. Setup Security Rules:
//    - Lihat security rules di week5_data_format.dart
//    - Apply di Firestore Rules

// 4. Setup Cloud Functions (untuk email notifications):
//    - Buka Cloud Functions
//    - Deploy function sesuai contoh di week5_email_service.dart

// ========== FIREBASE CONSOLE LINK ==========
// Ganti PROJECT_ID dengan project ID Anda:
// https://console.firebase.google.com/project/PROJECT_ID
