// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTXNIgNQbHbhjyY1sGQjgSHV_OpOgci_0',
    appId: '1:14085878797:web:39dd8a5cf0be0bdd471144',
    messagingSenderId: '14085878797',
    projectId: 'aplikasi-mobile-lanjut',
    authDomain: 'aplikasi-mobile-lanjut.firebaseapp.com',
    storageBucket: 'aplikasi-mobile-lanjut.firebasestorage.app',
    measurementId: 'G-JB15ZBZ9X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvgZgyAHIE_nuF9zsP1C6lDYkyGwBeGa8',
    appId: '1:14085878797:android:80675fefa4b3aaef471144',
    messagingSenderId: '14085878797',
    projectId: 'aplikasi-mobile-lanjut',
    storageBucket: 'aplikasi-mobile-lanjut.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTXNIgNQbHbhjyY1sGQjgSHV_OpOgci_0',
    appId: '1:14085878797:web:9bdebe077f0dfc68471144',
    messagingSenderId: '14085878797',
    projectId: 'aplikasi-mobile-lanjut',
    authDomain: 'aplikasi-mobile-lanjut.firebaseapp.com',
    storageBucket: 'aplikasi-mobile-lanjut.firebasestorage.app',
    measurementId: 'G-7TCN8TDHHQ',
  );
}
